language: node_js
node_js:
  - "10"
  - "8"
cache: npm
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-editing"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
